//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportSquad.Core.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SportSquad.Core.Resource.ApiResource", typeof(ApiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quantidade de times não pode ser vazia..
        /// </summary>
        public static string ASSEMBLED_TEAM_QUANTITY_TEAM_EMPTY {
            get {
                return ResourceManager.GetString("ASSEMBLED-TEAM-QUANTITY_TEAM_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O squad deve possuir configurações para a quantidade de jogadores..
        /// </summary>
        public static string CREATE_SQUAD_SQUAD_CONFIGS_EMPTY {
            get {
                return ResourceManager.GetString("CREATE-SQUAD-SQUAD_CONFIGS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houve um erro ao buscar seus squads, tente novamente mais tarde..
        /// </summary>
        public static string GET_SQUAD_BY_USER_USER_ID_EMPTY {
            get {
                return ResourceManager.GetString("GET-SQUAD-BY-USER-USER_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email não pode ser vazio..
        /// </summary>
        public static string LOGIN_REQUEST_EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("LOGIN-REQUEST-EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email deve ser um email válido..
        /// </summary>
        public static string LOGIN_REQUEST_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("LOGIN-REQUEST-INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O numero de telefone deve possuir &apos;{0}&apos; caracteres numéricos..
        /// </summary>
        public static string LOGIN_REQUEST_INVALID_NUMBER_CHARACTERS {
            get {
                return ResourceManager.GetString("LOGIN-REQUEST-INVALID_NUMBER_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha não pode ser vazia..
        /// </summary>
        public static string LOGIN_REQUEST_PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("LOGIN-REQUEST-PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número de telefone não pode ser vazio..
        /// </summary>
        public static string LOGIN_REQUEST_PHONE_NUMBER_EMPTY {
            get {
                return ResourceManager.GetString("LOGIN-REQUEST-PHONE_NUMBER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número de telefone deve ter {0} caracteres numéricos..
        /// </summary>
        public static string LOGIN_REQUEST_PHONE_NUMBER_INVALID {
            get {
                return ResourceManager.GetString("LOGIN-REQUEST-PHONE_NUMBER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número de telefone não pode ser vazio..
        /// </summary>
        public static string LOGIN_REQUEST_PHONE_NUMER_EMPTY {
            get {
                return ResourceManager.GetString("LOGIN-REQUEST-PHONE_NUMER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O id do jogador não pode ser vazio..
        /// </summary>
        public static string PLAYER_ID_EMPTY {
            get {
                return ResourceManager.GetString("PLAYER-ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome não pode ser vazio..
        /// </summary>
        public static string PLAYER_NAME_EMPTY {
            get {
                return ResourceManager.GetString("PLAYER-NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome deve possuir de &apos;{0}&apos; a &apos;{1}&apos; caracteres..
        /// </summary>
        public static string PLAYER_NAME_INVALID_NUMBER_CHARACTERS {
            get {
                return ResourceManager.GetString("PLAYER-NAME_INVALID_NUMBER_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado nenhum jogador com este id &apos;{0}&apos;..
        /// </summary>
        public static string PLAYER_NOT_FOUND_BY_ID {
            get {
                return ResourceManager.GetString("PLAYER-NOT_FOUND_BY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de jogador não pode ser vazio..
        /// </summary>
        public static string PLAYER_PLAYER_TYPE_ID_EMPTY {
            get {
                return ResourceManager.GetString("PLAYER-PLAYER_TYPE_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O squad não pode ser vazio..
        /// </summary>
        public static string PLAYER_SQUAD_ID_EMPTY {
            get {
                return ResourceManager.GetString("PLAYER-SQUAD_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O icone do tipo de jogador não pode ser vazio..
        /// </summary>
        public static string PLAYER_TYPE_ICON_EMPTY {
            get {
                return ResourceManager.GetString("PLAYER-TYPE-ICON_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do tipo de jogador deve ter entre &apos;{0}&apos; e &apos;{1}&apos; caracteres..
        /// </summary>
        public static string PLAYER_TYPE_INVALID_NUMBER_CHARACTERS {
            get {
                return ResourceManager.GetString("PLAYER-TYPE_INVALID_NUMBER_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do tipo de jogador não pode ser vazio..
        /// </summary>
        public static string PLAYER_TYPE_NAME_EMPTY {
            get {
                return ResourceManager.GetString("PLAYER-TYPE-NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado nenhum tipo de jogador com este id &apos;{0}&apos;..
        /// </summary>
        public static string PLAYER_TYPE_NOT_FOUND_BY_ID {
            get {
                return ResourceManager.GetString("PLAYER-TYPE-NOT_FOUND_BY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário não pode ser vazio..
        /// </summary>
        public static string PLAYER_USER_ID_EMPTY {
            get {
                return ResourceManager.GetString("PLAYER-USER_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O id da configuração do squad não pode ser vazio..
        /// </summary>
        public static string SQUAD_CONFIG_ID_EMPTY {
            get {
                return ResourceManager.GetString("SQUAD-CONFIG-ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrada nenhuma configuração de squad com este id &apos;{0}&apos;.
        /// </summary>
        public static string SQUAD_CONFIG_NOT_FOUND_BY_ID {
            get {
                return ResourceManager.GetString("SQUAD-CONFIG-NOT_FOUND_BY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de jogador da configuração de squad não pode ser vazio..
        /// </summary>
        public static string SQUAD_CONFIG_PLAYER_TYPE_ID_EMPTY {
            get {
                return ResourceManager.GetString("SQUAD-CONFIG-PLAYER_TYPE_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quantidade de jogadores para a configuração do squad não pode ser vazia..
        /// </summary>
        public static string SQUAD_CONFIG_QUANTITY_PLAYERS_EMPTY {
            get {
                return ResourceManager.GetString("SQUAD-CONFIG-QUANTITY_PLAYERS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O squad da configuração de squad não pode ser vazia..
        /// </summary>
        public static string SQUAD_CONFIG_SQUAD_ID_EMPTY {
            get {
                return ResourceManager.GetString("SQUAD-CONFIG-SQUAD_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível adicionar mais jogadores para esse tipo de jogador, pois a lista foi completada..
        /// </summary>
        public static string SQUAD_EXCEEDED_MAX_PLAYERS {
            get {
                return ResourceManager.GetString("SQUAD-EXCEEDED_MAX_PLAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já esxiste um squad com este mesmo nome &apos;{0}&apos;. Especifique outro nome, ou exclua o anterior..
        /// </summary>
        public static string SQUAD_EXISTING_SQUAD {
            get {
                return ResourceManager.GetString("SQUAD-EXISTING_SQUAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O id do squad não pode ser vazio..
        /// </summary>
        public static string SQUAD_ID_EMPTY {
            get {
                return ResourceManager.GetString("SQUAD-ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do squad deve ter entre &apos;{0}&apos; e &apos;{1}&apos; caracteres..
        /// </summary>
        public static string SQUAD_INVALID_NUMBER_CHARACTERS {
            get {
                return ResourceManager.GetString("SQUAD-INVALID_NUMBER_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do squad não pode ser vazio..
        /// </summary>
        public static string SQUAD_NAME_EMPTY {
            get {
                return ResourceManager.GetString("SQUAD-NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado nenhum squad com este id &apos;{0}&apos;..
        /// </summary>
        public static string SQUAD_NOT_FOUND_BY_ID {
            get {
                return ResourceManager.GetString("SQUAD-NOT_FOUND_BY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um nome igual a este neste squad. Tente mudar o sobre nome ou usar um apelido conhecido..
        /// </summary>
        public static string SQUAD_PLAYER_NAME_DUPLICATED {
            get {
                return ResourceManager.GetString("SQUAD-PLAYER-NAME_DUPLICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário do squad não pode ser vazio..
        /// </summary>
        public static string SQUAD_USER_ID_EMPTY {
            get {
                return ResourceManager.GetString("SQUAD-USER_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este squad não possui jogadores. Adicione jogadores a lista..
        /// </summary>
        public static string SQUAD_WITHOUT_PLAYERS {
            get {
                return ResourceManager.GetString("SQUAD-WITHOUT_PLAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O DDD não pode ser vazio..
        /// </summary>
        public static string USER_DDD_EMPTY {
            get {
                return ResourceManager.GetString("USER-DDD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O DDD deve possuir &apos;{0}&apos; caracteres numéricos..
        /// </summary>
        public static string USER_DDD_INVALID_NUMBER_CHARACTERS {
            get {
                return ResourceManager.GetString("USER-DDD_INVALID_NUMBER_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email do usuário não pode ser vazio..
        /// </summary>
        public static string USER_EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("USER-EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email do usuário deve ser um email válido..
        /// </summary>
        public static string USER_EMAIL_INVALID {
            get {
                return ResourceManager.GetString("USER-EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um usuário com o mesmo número de telefone..
        /// </summary>
        public static string USER_EXISTING_USER {
            get {
                return ResourceManager.GetString("USER-EXISTING_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ou senha incorretos. Verifique os dados inseridos..
        /// </summary>
        public static string USER_INVALID_LOGIN {
            get {
                return ResourceManager.GetString("USER-INVALID_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do usuário não pode ser vazio..
        /// </summary>
        public static string USER_NAME_EMPTY {
            get {
                return ResourceManager.GetString("USER-NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do usuário deve ter entre &apos;{0}&apos; e &apos;{1}&apos; caracteres..
        /// </summary>
        public static string USER_NAME_INVALID_NUMBER_CHARACTERS {
            get {
                return ResourceManager.GetString("USER-NAME_INVALID_NUMBER_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado nenhum usuário com este id &apos;{0}&apos;..
        /// </summary>
        public static string USER_NOT_FOUND_BY_ID {
            get {
                return ResourceManager.GetString("USER-NOT_FOUND_BY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha do usuário não pode ser vazia..
        /// </summary>
        public static string USER_PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("USER-PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O numero de telefone do usuário não pode ser vazio..
        /// </summary>
        public static string USER_PHONE_NUMBER_EMPTY {
            get {
                return ResourceManager.GetString("USER-PHONE_NUMBER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O numero de telefone do usuário deve possuir &apos;{0}&apos; caracteres numéricos..
        /// </summary>
        public static string USER_PHONE_NUMBER_INVALID_NUMBER_CHARACTERS {
            get {
                return ResourceManager.GetString("USER-PHONE_NUMBER_INVALID_NUMBER_CHARACTERS", resourceCulture);
            }
        }
    }
}
